#!/usr/bin/python
from sys import sys

with open(argv[i]) as f:
    for line in f:
        num = int(line.strip())
        print("{:d}m".format(num), end='')
        if num % 2 == 0:
            print(" * 2")
            continue
        factors = find_prime_factors(num)
        for factor in factors:
            print(" * {}".format(factor), end='')
        print()
