#!/usr/bin/python
import sys


def find_prime_factors(num):
    factors = []
    while num % 2 == 0:
        factors.append(2)
        num //= 2
    divisor = 3
    while divisor * divisor <= num:
        if num % divisor == 0:
            factors.append(divisor)
            num //= divisor
        else:
            divisor += 2
    if num != 1:
        factors.append(num)
    return factors


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py <filename>")
        sys.exit(1)

    filename = sys.argv[1]
    with open(filename) as f:
        for line in f:
            num = int(line.strip())
            print("{:d}m".format(num), end='')
            if num % 2 == 0:
                print(" * 2")
                continue
            factors = find_prime_factors(num)
            for factor in factors:
                print(" * {}".format(factor), end='')
            print()
